/*
 * Output values for the naming module demonstration.  These outputs
 * make it easy to verify that names are being generated correctly
 * without examining the state file.  For the multi‑environment
 * scenario, the outputs are maps keyed by environment name.
 */

output "resource_group_name" {
  description = "Generated name for the single environment resource group."
  value       = azurerm_resource_group.rg.name
}

output "storage_account_name" {
  description = "Globally unique storage account name generated by the naming module."
  value       = azurerm_storage_account.storage.name
}

output "virtual_network_name" {
  description = "Name for the virtual network in the single environment."
  value       = azurerm_virtual_network.vnet.name
}

output "subnet_name" {
  description = "Name for the subnet in the single environment."
  value       = azurerm_subnet.subnet.name
}

output "multi_resource_group_names" {
  description = "Map of resource group names by environment for the multi‑deployment scenario."
  value       = { for env, rg in azurerm_resource_group.multi_rg : env => rg.name }
}

output "multi_storage_account_names" {
  description = "Map of storage account names by environment for the multi‑deployment scenario."
  value       = { for env, sa in azurerm_storage_account.multi_storage : env => sa.name }
}